### PR TITLE
feat: Apply monospace fonts

### PR DESCRIPTION
**Pull request by leonskim**
- This applies monospace fonts to the Timestamp so the other text in Timeline Commands are aligned.
- @rmevans9 Do you think we need a global style like the standalone version?

### CODE REVIEW

**Comment by rmevans9** [comment]
I think a global style would work however I am not sure how we would go about doing that without overriding the font in all of the application consuming these components. I am wondering if we have to bake the font list into the theme we use with styled components and just manually apply in all top level components that could be rendered and let CSS do its job to cascade it down.

**Comment by leonskim** [comment]
Yeah, I think having the font list into the theme would satisfy both flipper plugin and the standalone version. Let me know if you want to do that way, I'll create one and apply to the all the top level components.

**Comment by rmevans9** [comment]
Yes, lets do it that way. In standalone even if we blanket apply the font that will not cause trouble since we would use the same font list.

**Comment by rmevans9** [comment]
Actually after thinking about this a bit we could make this a bit easier. We could create a component that is just meant to wrap the entire reactotron UI that applies any top level styles. We would then wrap the entire reactotron section in it or the entire standalone app. This way we don't have to remember to do it on every component.

**Comment by leonskim** [comment]
Sorry I'm late, I like this change with the wrapper 👍  💯

**Pull request merged**
